query GetBook($id: uuid!) {
	books_by_pk(id: $id) {
		id
		allow_borrow
		authors
		cover_url
		description
		genre
		language
		page_count
		preview_link
		price
		published_year
		publisher
		quantity
		subtitle
		title
		reviews {
			dislike_count
			id
			like_count
			rating
			text
			reader {
				id
				username
            photo_url
			}
		}
		reviews_aggregate {
			aggregate {
				count
				avg {
					rating
				}
			}
		}
	}
}
