query GetBooks($limit: Int = 20) {
	books(limit: $limit) {
		id
		title
		price
		quantity
		authors
		allow_borrow
		cover_url
		reviews_aggregate {
			aggregate {
				count
				avg {
					rating
				}
			}
		}
	}
}
